version: '3.8'

services:
  xd-web-app:
    image: dwachholder/xd-web-app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: xd-web-app
